version: '3.7'
services:
  nginx:
    container_name: dev_web
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - web
  web:
    container_name: dev_backend
    build: .
    restart: always
    env_file: ./config/.backend.env
    command: gunicorn dishes_ordering.wsgi:application --bind 0.0.0.0:5000
    volumes:
     - .:/app
     - static_volume:/app/static
    depends_on:
      - db
  db:
    container_name: dev_db
    image: postgres:12.6
    restart: always
    ports:
      - 5432:5432
    env_file: ./config/.database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    container_name: dev_redis
    image: redis:alpine
  celery:
    container_name: dev_celery
    restart: always
    build: .
    command: celery -A dishes_ordering worker -l INFO
    volumes:
      - .:/app
    env_file: ./config/.backend.env
    depends_on:
      - web
      - db
      - redis

volumes:
  static_volume:
  postgres_data: