# Generated by Django 3.2.5 on 2021-07-17 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_orderingredients_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredients',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
