# Generated by Django 3.2.5 on 2021-07-26 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_auto_20210725_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='orderingredients',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.ingredient'),
        ),
    ]
