# Generated by Django 3.2.5 on 2021-08-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_auto_20210807_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dish_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dishes.dish'),
        ),
    ]
