# Generated by Django 3.2.5 on 2021-08-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_order_dish_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dish_id',
            new_name='dish',
        ),
    ]
